name: UpsideDownWorld
version: 1.0
author: cocoraid
api-version: 1.19
main: com.cocoraid.UpsideDownWorld
depend: []
commands:
    replacebiome:
        description: "Upside Down World"
        usage: "/replacebiome"
        aliases: [rb]



